### PR TITLE
#6 do not initialize bigquery options

### PR DESCRIPTION
**Pull request by xjrk58**
#6 do not initialize bigquery options by default
#23 added test ensuring that credentials option is used

### CODE REVIEW

**Comment by achelimed** [comment]
It works for me on AWS EMR!

**Comment by achelimed** [comment]
But how can we set `spark.read.format("bigquery").option("credentialsFile",` "</path/to/key/file>")` with an s3 location?

**Comment by dboyliao** [comment]
I build the connector with `sbt assembly` and add the jar to `spark.jars` in `PySpark`.
Passing the project id and table name as:
```python
sdf = (
    spark
    .format('bigquery')
    .option('project', 'myProject')
    .option('table', 'myTable')
    .load()
```

But I still get projectID not found error:
```python
Py4JJavaError: An error occurred while calling o121.load.
: java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
	at com.google.cloud.spark.bigquery.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:266)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:81)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:30)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryOptions$Builder.build(BigQueryOptions.java:76)
```

**Comment by xjrk58** [comment]
@dboyliao you have to specify as well `parentProject` parameter (billing project). Usually it's the same as `project`.

**Comment by dboyliao** [comment]
Oh, I see.
I'll try it at work.
Thanks a lot @xjrk58

**Comment by dboyliao** [comment]
It works on my AWS EC2!
Much faster than fetching data via python client library.
Really appreciate your work @xjrk58.

**Comment by achelimed** [comment]
Hi @xjrk58,
Could you tell me when this PR will be closed?

**Comment by xjrk58** [comment]
@achelimed I would rather ask someone with write access to this repository. (@pmkc or @aniket486 maybe)

**Comment by Quach90** [comment]
Can someone build this, I keep getting errors when running `sbt assembly`

**Comment by llKetanll** [comment]
@aniket486 @pmkc Any updates? What is holding up this PR from being merged?

**Comment by davidrabinowitz** [comment]
Hi @xjrk58 ,

Thanks for the patch! In order to merge it I need two things:

- Please check you have signed the CLA, signed the consent and the rest of the legal stuff. Unfortunately I cannot touch this code until you do.
- Much have changed since the original contribution, can you please rebase your code on the latest master?

Thanks
David

**Comment by xjrk58** [comment]
I signed it!

**Comment by davidrabinowitz** [comment]
I've fixed the CLA issue. Can you please have a look at the merge conflicts?

**Comment by vprus** [comment]
The merge conflicts all appear to be trivial. I have a branch with those conflicts resolved at https://github.com/vprus/spark-bigquery-connector/commits/auth-outside-gcp - and the only non-mechanical change was checking for a different exception type and message in the test. Hope this helps.

**Comment by xjrk58** [comment]
@davidrabinowitz looks like that CLA issue appeared again. 

Meanwhile I've resolved merge conflicts, so feel free to merge this PR.

**Comment by xjrk58** [comment]
@googlebot I consent.

**Comment by davidrabinowitz** [comment]
@xjrk58 Thanks for that! The CLA issue is because the email of the last commit (***@***.de) is different from the email of the CLA (***@***.com). Can you please push your commit with the original e-mail?

@vprus Thanks for the contribution! We'd be happy to receive more in the future, but we need you to sign the CLA first. If you haven't done it already, you can do that in https://cla.developers.google.com/. Thanks!

**Comment by xjrk58** [comment]
@davidrabinowitz it rather looks like an issue with one of my previous commits. I've replaced all previous commits with a single one, so hopefully it's fine now.

**Pull request merged**
